name: Build & Deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run formatter
        run: yarn format

      - name: Run eslint
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Cache build for deployment
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./dist
            ./package.json
            ./pm2.yml
            ./tsconfig-paths-bootstrap.js
            ./tsconfig.json
            ./yarn.lock
            ./procfile
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

  deploy:
    name: Deploy to heroku

    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    if: github.ref == 'refs/head/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache build for deployment
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./dist
            ./package.json
            ./pm2.yml
            ./tsconfig-paths-bootstrap.js
            ./tsconfig.json
            ./yarn.lock
            ./procfile
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}"
          heroku_email: "${{ secrets.HEROKU_USER_EMAIL }}"
          procfile: "worker: npm start"
        env:
          HD_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          HD_DETECTLANGUAGE_API_KEY: ${{ secrets.DETECTLANGUAGE_API_KEY }}
          HD_RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          HD_DEVELOPER_TEST_SERVER: ${{ secrets.DEVELOPER_TEST_SERVER }}
          HD_OWNER_IDS: ${{ secrets.OWNER_IDS }}
