name: test and build

on:
  push:
    branches:
      - main

  pull_request:
    brances:
      - main

jobs:
  test_and_build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run formatter
        run: yarn format

      - name: Run eslint
        run: yarn lint

      - name: Run build
        run: yarn build

  deploy:
    name: Deploy to heroku

    needs: test_and_build

    env:
      project-id: "${{ secrets.projectId }}"
      auth-token: "${{ secrets.authToken }}"

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}"
          heroku_email: "${{ secrets.HEROKU_USER_EMAIL }}"
        env:
          DISCORD_TOKENL: ${{ secrets.DISCORD_TOKEN }}
          DETECTLANGUAGE_API_KEY: ${{ secrets.DETECTLANGUAGE_API_KEY }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          DEVELOPER_TEST_SERVER: ${{ secrets.DEVELOPER_TEST_SERVER }}
          OWNER_IDS: ${{ secrets.OWNER_IDS }}
