name: test and build

on:
  push:
    branches: [main]

  pull_request:
    brances: [main]

jobs:
  test_and_build:
    name: Test & Build

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: User Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
